### ISSUE TITLE
I tried to fill the absent codes, but failed!

### ISSUE THREAD

**Issue by YANGGANG1971** [vvv-school/assignment_motor-control#2]
Here is the result. It may be caused by that trigger/output is unavailable. 
May I get the correct codes and check it by myself?
In addition, to positionMove(int j, double ref) function, j refers to joint number. May I know the elaborated corresponding relations? for instance, what is 1 (2, 3 and 4) refers to?
![image](https://user-images.githubusercontent.com/55526431/69127828-5c953d00-0aee-11ea-9951-aab4b8acd1e0.png)

**Comment by pattacini** [comment]
You can download the solution from this link: https://send.firefox.com/download/2e257e1305986bf2/#mM3LIwR_9wr8ZCxMCu4ePA.

It will expire after 100 downloads or 7 days.
